language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - {python: '3.5'}
    - {python: '3.6'}
    - {python: '3.7'}
    - {python: '3.8'}

    - {env: TOXENV=docs, python: '3.7'}
    - {env: TOXENV=quality, python: '3.7'}

install:
  - travis_retry pip install tox tox-travis

script:
  - tox
