language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - {python: '3.8'}
    - {python: '3.9'}
    - {python: '3.10'}
    - {python: '3.11'}
    - {python: '3.12'}

    - {env: TOXENV=docs, python: '3.12'}
    - {env: TOXENV=quality, python: '3.12'}

install:
  - travis_retry pip install tox tox-travis

script:
  - tox
