name: Publish Python distribution to PyPI

on: push

jobs:
  publish-to-pypi:
    name: Publish Python distribution to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/xlsx_streaming
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install pypa/build
      run: pip install build
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
